spring:
  datasource:
    username: #Login#
    password: #Password#
    url: jdbc:mysql://localhost:3306/todolist1?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true